[package]
name = "llm-telegram-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = { version = "0.17", features = ["macros"] }
tokio = { version = "1.8", features = ["full"] }
openai = { version = "1" }
serde = { version = "1", features = ["derive"] }
dotenvy = { version = "0.15" }
anyhow = { version = "1" }
envy = { version = "0.4" }
